# Site settings
title: Luke Overstreet | Media & Communications Specialist
email: youremailaddress@gmail.com
description: Professional photography, videography, graphic design, and social media services in the greater Quad City area.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url: https://facebook.com
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/lukeoverstreet/
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
