# Site settings
title: Luke Overstreet | Media & Communications Specialist
email: luke.overstreet@outlook.com
description: Professional photography, videography, graphic design, and social media services in the greater Quad City area.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/lukeoverstreet/
linkedin_url: https://www.linkedin.com/in/lukeoverstreet/
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
